### ISSUE TITLE
Show balance(s) on account(s)

### ISSUE THREAD

**Issue by nc534** [RaymondMoorhead/DollarsBankFullStack#22]
Users should be able to view the balance of their owned accounts.

![image](https://user-images.githubusercontent.com/44171274/92663021-2370c800-f2ce-11ea-92aa-abd3903bf650.png)

**Comment by erunseelie** [comment]
Closed in dedac94f6fc5414622856ab59f5320b6475a5a7a.

![image](https://user-images.githubusercontent.com/44171274/92665115-ba8c4e80-f2d3-11ea-81c4-9472435ac8dc.png)
